
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.core.annotation.Optional;

  
  class _0_com_zkty_jsi_media_DTO {
    public Integer index;

    public List<String> imgList;
  }
  
  class _1_com_zkty_jsi_media_DTO {
    public Integer status;
  }
  
  class _2_com_zkty_jsi_media_DTO {
    public String type;

    public String imageData;
  }
  
  class _3_com_zkty_jsi_media_DTO {
    @Optional
		public boolean allowsEditing;

    @Optional
		public boolean savePhotosAlbum;

    @Optional
		public Integer cameraFlashMode;

    @Optional
		public String cameraDevice;

    public boolean isbase64;

    @Optional
		public Map<String,String> args;

    @Optional
		public Integer photoCount;
  }
  
  class _4_com_zkty_jsi_media_DTO {
    public String url;

    public Map<String,String> header;

    public List ids;
  }
  
  interface xengine_jsi_media_protocol {
    
public void _previewImg(_0_com_zkty_jsi_media_DTO dto);
public void _saveImageToPhotoAlbum(_2_com_zkty_jsi_media_DTO dto, final CompletionHandler<_1_com_zkty_jsi_media_DTO> handler);
public void _openImagePicker(_3_com_zkty_jsi_media_DTO dto, final CompletionHandler<String> handler);
public void _uploadImage(_4_com_zkty_jsi_media_DTO dto, final CompletionHandler<String> handler);
  }
  
  
    public abstract class xengine_jsi_media extends JSIModule implements xengine_jsi_media_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.media";
    }
  
        @JavascriptInterface
        public Object previewImg(JSONObject jsonobj) {
          _0_com_zkty_jsi_media_DTO dto= convert(jsonobj,_0_com_zkty_jsi_media_DTO.class);
          _previewImg(dto);
          return null;
        }
        

    @JavascriptInterface
    final public void saveImageToPhotoAlbum(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _2_com_zkty_jsi_media_DTO dto= convert(jsonobj,_2_com_zkty_jsi_media_DTO.class);
      _saveImageToPhotoAlbum(dto, new CompletionHandler<_1_com_zkty_jsi_media_DTO>() {
        @Override
        public void complete(_1_com_zkty_jsi_media_DTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(_1_com_zkty_jsi_media_DTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void openImagePicker(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _3_com_zkty_jsi_media_DTO dto= convert(jsonobj,_3_com_zkty_jsi_media_DTO.class);
      _openImagePicker(dto, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void uploadImage(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _4_com_zkty_jsi_media_DTO dto= convert(jsonobj,_4_com_zkty_jsi_media_DTO.class);
      _uploadImage(dto, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }
  }
  

  