
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi.device;

  import android.webkit.JavascriptInterface;

  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.JSIModule;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;


class phoneDto {
    public String phoneNum;

    public String phoneMsg;
  }
  
  class DeviceDTO {
    public String type;

    public String systemVersion;

    public String language;

    public String UDID;
  }
  
  interface xengine_jsi_device_protocol {
        String _getStatusBarHeight();
    String _getNavigationHeight();
    String _getScreenHeight();
    String _getTabbarHeight();
    String _getSystemVersion();
    String _getUDID();
    String _callPhone(phoneDto dto);
    String _sendMessage(phoneDto dto);
    String _getDeviceInfo();
public void _getDeviceInfo1(final CompletionHandler<DeviceDTO> handler);
  }
  
  
  public abstract class xengine_jsi_device extends JSIModule implements xengine_jsi_device_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.device";
    }
  
        @JavascriptInterface
        public String getStatusBarHeight(JSONObject jsonobj) {
          
          return _getStatusBarHeight();
        }
        

        @JavascriptInterface
        public String getNavigationHeight(JSONObject jsonobj) {
          
          return _getNavigationHeight();
        }
        

        @JavascriptInterface
        public String getScreenHeight(JSONObject jsonobj) {
          
          return _getScreenHeight();
        }
        

        @JavascriptInterface
        public String getTabbarHeight(JSONObject jsonobj) {
          
          return _getTabbarHeight();
        }
        

        @JavascriptInterface
        public String getSystemVersion(JSONObject jsonobj) {
          
          return _getSystemVersion();
        }
        

        @JavascriptInterface
        public String getUDID(JSONObject jsonobj) {
          
          return _getUDID();
        }
        

        @JavascriptInterface
        public String callPhone(JSONObject jsonobj) {
          phoneDto data= convert(jsonobj,phoneDto.class);
          return _callPhone(data);
        }
        

        @JavascriptInterface
        public String sendMessage(JSONObject jsonobj) {
          phoneDto data= convert(jsonobj,phoneDto.class);
          return _sendMessage(data);
        }
        

        @JavascriptInterface
        public String getDeviceInfo(JSONObject jsonobj) {
          
          return _getDeviceInfo();
        }
        

    @JavascriptInterface
    final public void getDeviceInfo1(JSONObject obj, final CompletionHandler<Object> handler) {
      _getDeviceInfo1(new CompletionHandler<DeviceDTO>() {
        @Override
        public void complete(DeviceDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(DeviceDTO value) { handler.setProgressData(value); }
      });

    }
  }
  

  