# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/zkty-team/x-engine-pods.git'

target 'camera' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

		
 pod "GCDWebServer"

# Pods for XEngineSDK
# 在开发时,将所有依赖的 module 包放这.包括依赖的依赖
  pod 'x-engine-module-engine', :path =>'../../x-engine-module-engine'
  pod 'x-engine-module-protocols', :path =>'../../x-engine-module-protocols/'
  #pod 'x-engine-module-microapp', :path =>'../../x-engine-module-microapp'
  pod 'x-engine-module-tools', :path =>'../../x-engine-module-tools'
  target 'cameraUITests' do
    # Pods for testing
  end

end
