// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.lope", 
    [
  {
    "name": "openDoor",
    "default_args": {
      "serviceUUID": [
        "2560",
        "FEE7"
      ]
    }
  },
  {
    "name": "customOpenDoor",
    "default_args": {}
  },
  {
    "name": "lightLift",
    "default_args": {}
  },
  {
    "name": "haveArgRetPrimitive",
    "default_args": {
      "title": "abc"
    }
  }
]
)}}

export default osCheck();
