// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.lope", 
    [
  {
    "name": "initSdkAndConfigure",
    "default_args": {
      "pid": "03jfuto709chalfwo84nf921qujt5p"
    }
  },
  {
    "name": "scanDevice",
    "default_args": {
      "interval": 1,
      "serviceUUIDs": [
        "2560",
        "FEE7"
      ],
      "immediately": false
    }
  },
  {
    "name": "openDoor",
    "default_args": {
      "locks": [
        {
          "mac": "00:18:E4:0C:73:89",
          "key": "12345678"
        },
        {
          "mac": "00:18:E4:0C:6C:21",
          "key": "12345678"
        }
      ]
    }
  },
  {
    "name": "lightLift",
    "default_args": {
      "mac": "B0:7E:11:F4:D9:94",
      "ioIndex": 4
    }
  }
]
)}}

export default osCheck();
