// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.device", 
    [
  {
    "name": "getPhoneType",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getSystemVersion",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getUDID",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getBatteryLevel",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getPreferredLanguage",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getScreenWidth",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getScreenHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getSafeAreaTop",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getSafeAreaBottom",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getSafeAreaLeft",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getSafeAreaRight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getStatusHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getNavigationHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "getTabBarHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "devicePhoneCall",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "deviceSendMessage",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
