
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

package com.zkty.jsi;
import java.util.List;
import java.util.Map;
import java.util.Set;
import android.webkit.JavascriptInterface;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.zkty.nativ.jsi.bridge.CompletionHandler;
import com.zkty.nativ.jsi.JSIModule;
import androidx.annotation.Nullable;
import com.zkty.nativ.core.annotation.Optional;


class LocationDTO {
  public String longitude;

    public String latitude;

    public String address;

    public String country;

    public String province;

    public String city;

    public String district;

    public String street;
  }

interface xengine_jsi_geo_protocol {
  public void _locate(final CompletionHandler<LocationDTO> handler);
}
  

    public abstract class xengine_jsi_geo extends JSIModule implements xengine_jsi_geo_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.geo";
    }
  
    @JavascriptInterface
    final public void locate(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _locate(new CompletionHandler<LocationDTO>() {
        @Override
        public void complete(LocationDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(LocationDTO value) { handler.setProgressData(value); }
      });

    }
  }
  

  