# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
source 'https://github.com/CocoaPods/Specs.git'

X_ENGINE_MODULES=ENV['X_ENGINE_MODULES'] || '../..'

def shared_pods
  pod 'x-engine-native-core', :path =>X_ENGINE_MODULES+'/x-engine-native-core'
  pod 'x-engine-native-jsi', :path =>X_ENGINE_MODULES+'/x-engine-native-jsi'
  pod 'x-engine-native-direct_omp', :path =>X_ENGINE_MODULES+'/x-engine-native-direct_omp'
  pod 'x-engine-native-direct_microapp', :path =>X_ENGINE_MODULES+'/x-engine-native-direct_microapp'
  pod 'x-engine-native-viewer_original', :path =>X_ENGINE_MODULES+'/x-engine-native-viewer_original'
  pod 'x-engine-native-viewer',          :path =>X_ENGINE_MODULES+'/x-engine-native-viewer'
  pod 'x-engine-native-store',           :path =>X_ENGINE_MODULES+'/x-engine-native-store'
  pod 'x-engine-native-protocols',       :path =>X_ENGINE_MODULES+'/x-engine-native-protocols'
  pod 'x-engine-native-direct',          :path =>X_ENGINE_MODULES+'/x-engine-native-direct'

  pod "MBProgressHUD"
  pod "AFNetworking"
  
end

target 'viewer' do
  #use_frameworks!
  shared_pods
end
target 'viewerTests' do
  #use_frameworks!
  shared_pods
end
target 'viewerUITests' do
  # Pods for testing
  shared_pods

end
