// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.network", 
    [
  {
    "name": "getRequest",
    "default_args": {
      "url": "",
      "method": "get"
    },
    "decorators": []
  },
  {
    "name": "postRequest",
    "default_args": {
      "url": "",
      "method": "post"
    },
    "decorators": []
  },
  {
    "name": "deleteRequest",
    "default_args": {
      "url": "",
      "method": "delete"
    },
    "decorators": []
  },
  {
    "name": "headRequest",
    "default_args": {
      "url": "",
      "method": "head"
    },
    "decorators": []
  },
  {
    "name": "putRequest",
    "default_args": {
      "url": "",
      "method": "put"
    },
    "decorators": []
  },
  {
    "name": "patchRequest",
    "default_args": {
      "url": "",
      "method": "patch"
    },
    "decorators": []
  },
  {
    "name": "downloadRequest",
    "default_args": {
      "url": "",
      "method": "POST",
      "isNeedBase64": false
    },
    "decorators": []
  },
  {
    "name": "uploadRequest",
    "default_args": {
      "url": "",
      "method": "POST"
    },
    "decorators": []
  }
]
)}}

export default osCheck();
