# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ModuleApp' do
 
 target 'ModuleAppTests' do
    inherit! :search_paths
  end

  target 'ModuleAppUITests' do
  end

end
