# Uncomment thj next line to define a global platform for your project
platform :ios, '10.0'


target 'ModuleApp' do
    #inherit! :search_paths
    #pod 'UniBoost', :path => '../../../../UniBoost'
    pod 'JSONModel'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'SSZipArchive'
    pod 'WechatOpenSDK'
 
 target 'ModuleAppTests' do
  end

  target 'ModuleAppUITests' do
  end

end
