# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ModuleApp' do
 
 target 'ModuleAppTests' do
    inherit! :search_paths
    pod 'UniBoost', :path => '../../../../UniBoost'
    pod 'JSONModel'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'SSZipArchive'
    pod 'WechatOpenSDK'
  end

  target 'ModuleAppUITests' do
  end

end
