
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.jsi.annotation.Optional;

  
  
  interface xengine_jsi_localstorage_protocol {
    public void _get(String dto, final CompletionHandler<String> handler);    String _get(String dto);
public void _set(String dto, final CompletionHandler<Nullable> handler);    void _set(String dto);
  }
  
  
  public abstract class xengine_jsi_localstorage extends JSIModule implements xengine_jsi_localstorage_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.localstorage";
    }
  
    @JavascriptInterface
    final public void get(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      String dto= convert(jsonobj,String.class);
      _get(dto, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }
        @JavascriptInterface
        public String get(JSONObject jsonobj) {
          String dto= convert(jsonobj,String.class);
          return _get(dto);
        }
        

    @JavascriptInterface
    final public void set(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      String dto= convert(jsonobj,String.class);
      _set(dto, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
        @JavascriptInterface
        public Object set(JSONObject jsonobj) {
          String dto= convert(jsonobj,String.class);
          _set(dto);
          return null;
        }
        
  }
  

  