
// WARNING.
// generated by api_generator.js,
// Do not modify this file. It will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class SheetDTO {
    public String __event__;
  }
  
  class MoreDTO {
    public String content;
  }
  
  interface xengine__module_device_i {
    public void _getPhoneType(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getSystemVersion(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getUDID(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getBatteryLevel(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getPreferredLanguage(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getScreenWidth(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getScreenHeight(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getSafeAreaTop(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getSafeAreaBottom(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getSafeAreaLeft(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getSafeAreaRight(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getStatusHeight(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getNavigationHeight(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
public void _getTabBarHeight(SheetDTO dto, final CompletionHandler<MoreDTO> handler);
  }
  
  
  public abstract class xengine__module_device extends xengine__module_BaseModule implements xengine__module_device_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.device";
    }
  
    @JavascriptInterface
    public void getPhoneType(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getPhoneType(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getSystemVersion(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getSystemVersion(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getUDID(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getUDID(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getBatteryLevel(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getBatteryLevel(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getPreferredLanguage(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getPreferredLanguage(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getScreenWidth(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getScreenWidth(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getScreenHeight(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getScreenHeight(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getSafeAreaTop(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getSafeAreaTop(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getSafeAreaBottom(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getSafeAreaBottom(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getSafeAreaLeft(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getSafeAreaLeft(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getSafeAreaRight(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getSafeAreaRight(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getStatusHeight(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getStatusHeight(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getNavigationHeight(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getNavigationHeight(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void getTabBarHeight(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _getTabBarHeight(data, new CompletionHandler<MoreDTO>() {
        @Override
        public void complete(MoreDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(MoreDTO value) { handler.setProgressData(value); }
      });

    }
  }
  

  