
// DO NOT MODIFY!.
// generated by api_generator.js, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class SheetDTO {
    public String title;

    @Optional
		public List<String> itemList;

    @Optional
		public String content;

    public String __event__;
  }
  
  interface xengine__module_demo_i {
    public void _noArgNoRet(final CompletionHandler<Nullable> handler);
    public void _noArgRetPrimitive(final CompletionHandler<String> handler);
    public void _noArgRetSheetDTO(final CompletionHandler<SheetDTO> handler);
    public void _haveArgNoRet(SheetDTO dto, final CompletionHandler<Nullable> handler);
    public void _haveArgRetPrimitive(SheetDTO dto, final CompletionHandler<String> handler);
    public void _haveArgRetSheetDTO(SheetDTO dto, final CompletionHandler<SheetDTO> handler);
    public void _showActionSheet(SheetDTO dto, final CompletionHandler<Nullable> handler);
  }
  
  
  public abstract class xengine__module_demo extends xengine__module_BaseModule implements xengine__module_demo_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.demo";
    }
  
    @JavascriptInterface
    final public void noArgNoRet(JSONObject obj, final CompletionHandler<Object> handler) {
      _noArgNoRet(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void noArgRetPrimitive(JSONObject obj, final CompletionHandler<Object> handler) {
      _noArgRetPrimitive(new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void noArgRetSheetDTO(JSONObject obj, final CompletionHandler<Object> handler) {
      _noArgRetSheetDTO(new CompletionHandler<SheetDTO>() {
        @Override
        public void complete(SheetDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(SheetDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void haveArgNoRet(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _haveArgNoRet(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void haveArgRetPrimitive(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _haveArgRetPrimitive(data, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void haveArgRetSheetDTO(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _haveArgRetSheetDTO(data, new CompletionHandler<SheetDTO>() {
        @Override
        public void complete(SheetDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(SheetDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void showActionSheet(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _showActionSheet(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  
