
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class SheetDTO {
    public String title;

    @Optional
		public List<String> itemList;

    @Optional
		public String content;

    public String __event__;
  }
  
  class ContinousDTO {
    @Optional
		public String __event__;
  }
  
  class MsgPayloadDTO {
    public String type;

    @Optional
		public Map<String,String> args;

    @Optional
		public String sender;

    @Optional
		public List<String> receiver;

    public String __event__;

    public String __ret__;
  }
  
  interface xengine__jsi_chat_i {
    public void _broadcastOn(final CompletionHandler<Nullable> handler);
public void _broadcastOff(final CompletionHandler<Nullable> handler);
public void _triggerNativeBroadCast(final CompletionHandler<Nullable> handler);
public void _repeatReturn__event__(ContinousDTO dto, final CompletionHandler<String> handler);
public void _repeatReturn__ret__(ContinousDTO dto, final CompletionHandler<String> handler);
public void _ReturnInPromiseThen(ContinousDTO dto, final CompletionHandler<String> handler);
  }
  
  
  public abstract class xengine__jsi_chat extends xengine__module_BaseModule implements xengine__jsi_chat_i {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.chat";
    }
  
    @JavascriptInterface
    final public void broadcastOn(JSONObject obj, final CompletionHandler<Object> handler) {
      _broadcastOn(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void broadcastOff(JSONObject obj, final CompletionHandler<Object> handler) {
      _broadcastOff(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void triggerNativeBroadCast(JSONObject obj, final CompletionHandler<Object> handler) {
      _triggerNativeBroadCast(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void repeatReturn__event__(JSONObject obj, final CompletionHandler<Object> handler) {
      ContinousDTO data= convert(obj,ContinousDTO.class);
      _repeatReturn__event__(data, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void repeatReturn__ret__(JSONObject obj, final CompletionHandler<Object> handler) {
      ContinousDTO data= convert(obj,ContinousDTO.class);
      _repeatReturn__ret__(data, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void ReturnInPromiseThen(JSONObject obj, final CompletionHandler<Object> handler) {
      ContinousDTO data= convert(obj,ContinousDTO.class);
      _ReturnInPromiseThen(data, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }
  }
  

  