# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zkty-team/x-engine-pods.git'

target 'offline' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'JSONModel'
  pod 'SSZipArchive'

#  pod 'DoraemonKit/Core', '~> 3.0.2', :configurations => ['Debug'] #Required
#  pod 'DoraemonKit/WithGPS', '~> 3.0.2', :configurations => ['Debug'] #Optional
#  pod 'DoraemonKit/WithLoad', '~> 3.0.2', :configurations => ['Debug'] #Optional

  pod 'x-engine-module-engine', :path =>'../../x-engine-module-engine'
  pod 'x-engine-module-network', :path =>'../../x-engine-module-network'
  pod 'x-engine-module-protocols', :path =>'../../x-engine-module-protocols'
  pod 'x-engine-module-tools', :path =>'../../x-engine-module-tools'
#  pod 'x-engine-module-microapp', :path =>'../../x-engine-module-microapp'
  pod 'x-engine-module-tools', :path =>'../../x-engine-module-tools'
  

  target 'offlineUITests' do

  end

end
