component: website
name: x-engine
app: x-engine-c336ae26

inputs:
  src:
    src: ./x-engine-docs
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: x-engine
  protocol: https
