
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

package com.zkty.jsi;
import java.util.List;
import java.util.Map;
import java.util.Set;
import android.webkit.JavascriptInterface;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.zkty.nativ.jsi.bridge.CompletionHandler;
import com.zkty.nativ.jsi.JSIModule;
import androidx.annotation.Nullable;
import com.zkty.nativ.core.annotation.Optional;


class ParameterInUrlReq {
    }
  
class ParameterInUrlRes {
    }

interface undefined_protocol {
  
}
  

    public abstract class undefined extends JSIModule implements undefined_protocol {
    @Override
    public String moduleId() {
      return "undefined";
    }
  
  }
  

  
		public String digest;

    @Optional
		public String externalUrl;

    @Optional
		public boolean isUpdate;

    @Optional
		public String remark;

    @Optional
		public String resUrl;

    @Optional
		public String title;

    @Optional
		public Integer type;
  }

interface undefined_protocol {
  
}
  

    public abstract class undefined extends JSIModule implements undefined_protocol {
    @Override
    public String moduleId() {
      return "undefined";
    }
  
  }
  

  c String userKey;
  }

interface undefined_protocol {
  
}
  

    public abstract class undefined extends JSIModule implements undefined_protocol {
    @Override
    public String moduleId() {
      return "undefined";
    }
  
  }
  

  