
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

package com.zkty.jsi;
import java.util.List;
import java.util.Map;
import java.util.Set;
import android.webkit.JavascriptInterface;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.zkty.nativ.jsi.bridge.CompletionHandler;
import com.zkty.nativ.jsi.JSIModule;
import androidx.annotation.Nullable;
import com.zkty.nativ.core.annotation.Optional;


class x_api_gm_general_login_Req {
  @Optional
		public Integer ldapId;

    @Optional
		public String password;

    @Optional
		public String username;
  }
  
class x_api_gm_general_login_Res {
  @Optional
		public String sessionToken;

    @Optional
		public String userToken;

    @Optional
		public _0__DTO bizUser;
  }
  
class _0__DTO {
  @Optional
		public String avatar;

    @Optional
		public String createdTime;

    @Optional
		public String email;

    @Optional
		public String genderType;

    @Optional
		public Integer id;

    @Optional
		public String nickname;

    @Optional
		public String phoneNum;

    @Optional
		public String realname;

    @Optional
		public Integer status;

    @Optional
		public String updatedTime;

    @Optional
		public String userKey;
  }

interface undefined_protocol {
  
}
  

    public abstract class undefined extends JSIModule implements undefined_protocol {
    @Override
    public String moduleId() {
      return "undefined";
    }
  
  }
  

  