
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import android.webkit.JavascriptInterface;

import com.zkty.nativ.jsi.JSIModule;

  
  
  interface xengine_jsi_secret_protocol {
        String _get(String dto);
  }
  
  
  public abstract class xengine_jsi_secret extends JSIModule implements xengine_jsi_secret_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.secret";
    }
  
        @JavascriptInterface
        public String get(String jsonobj) {
//          String dto= convert(jsonobj,String.class);
          return _get(jsonobj);
        }
        
  }
  

  