
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;

  
  
  interface xengine_jsi_secret_protocol {
    
public String _get(String dto);
  }
  
  
    public abstract class xengine_jsi_secret extends JSIModule implements xengine_jsi_secret_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.secret";
    }
  
        @JavascriptInterface
        public String get(String dto) {
          
          return _get(dto);
        }
        
  }
  

  