# Uncomment thj next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods
  pod 'x-engine-native-core', :path =>'../../x-engine-native-core'
  pod 'x-engine-native-protocols', :path =>'../../x-engine-native-protocols'
  pod 'JSONModel'
end

target 'ModuleApp' do
  shared_pods
end

target 'ModuleAppTests' do
end

target 'ModuleAppUITests' do
end
