# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
#source 'https://github.com/CocoaPods/Specs.git'

#load './ModulePods.rb'
target 'motherboard' do
  pod 'x-engine-jsi-engine', :path =>'../../modules/x-engine-jsi-engine'
  pod 'x-engine-jsi-protocols', :path =>'../../modules/x-engine-jsi-protocols/'
  pod 'ZBarSDK', :path =>'../../app/ios-thirdlib/ZBarSDK'
  pod 'x-engine-jsi-camera', :path =>'../../modules/x-engine-jsi-camera'
  pod 'x-engine-jsi-device', :path =>'../../modules/x-engine-jsi-device'
  pod 'x-engine-jsi-scan', :path =>'../../modules/x-engine-jsi-scan'

  
  target 'motherboardUITests' do
  end

end
