
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class DirectPushDTO {
    public String scheme;

    @Optional
		public String host;

    public String pathname;

    public String fragment;

    @Optional
		public Map<String,String> query;

    @Optional
		public Map<String,String> params;
  }
  
  class DirectBackDTO {
    public String scheme;

    public String fragment;
  }
  
  interface xengine__jsi_direct_i {
    public void _push(DirectPushDTO dto, final CompletionHandler<Nullable> handler);
public void _back(DirectBackDTO dto, final CompletionHandler<Nullable> handler);
  }
  
  
  public abstract class xengine__jsi_direct extends xengine__module_BaseModule implements xengine__jsi_direct_i {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.direct";
    }
  
    @JavascriptInterface
    final public void push(JSONObject obj, final CompletionHandler<Object> handler) {
      DirectPushDTO data= convert(obj,DirectPushDTO.class);
      _push(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void back(JSONObject obj, final CompletionHandler<Object> handler) {
      DirectBackDTO data= convert(obj,DirectBackDTO.class);
      _back(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  