// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.camera", 
    [
  {
    "name": "openImagePicker",
    "default_args": {
      "allowsEditing": true,
      "savePhotosAlbum": false,
      "cameraFlashMode": -1,
      "cameraDevice": "back",
      "photoCount": 1
    }
  },
  {
    "name": "saveImageToAlbum",
    "default_args": {
      "type": "url"
    }
  }
]
)}}

export default osCheck();
