// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.camera", 
    [
  {
    "name": "openImagePicker",
    "default_args": {
      "allowsEditing": true,
      "savePhotosAlbum": false,
      "cameraFlashMode": -1,
      "cameraDevice": "back",
      "isbase64": true,
      "width": "200",
      "height": "100",
      "quality": "0.5",
      "bytes": "1024"
    }
  }
]
)}}

export default osCheck();
