
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class TZCashDTO {
    public String orderNoList;

    public String businessCstNo;

    public String platMerCstNo;

    public String frontBackUrl;

    public String __event__;
  }
  
  class TZCashRetDTO {
    public String orderStatus;
  }
  
  interface xengine__module_tzcash_i {
    public void _callPaymentSDK(TZCashDTO dto, final CompletionHandler<TZCashRetDTO> handler);
  }
  
  
  public abstract class xengine__module_tzcash extends xengine__module_BaseModule implements xengine__module_tzcash_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.tzcash";
    }
  
    @JavascriptInterface
    final public void callPaymentSDK(JSONObject obj, final CompletionHandler<Object> handler) {
      TZCashDTO data= convert(obj,TZCashDTO.class);
      _callPaymentSDK(data, new CompletionHandler<TZCashRetDTO>() {
        @Override
        public void complete(TZCashRetDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(TZCashRetDTO value) { handler.setProgressData(value); }
      });

    }
  }
  

  