
// MODIFIALBE! 
// generated by api_generator.js,
// only generated when file is not existed!

export default {
    noArgNoRet(args={},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert(JSON.stringify(args));
          resolve(null);
        });
      }

    }
    ,
    
    noArgRetPrimitive(args={},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("noArgRetPrimitive no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    noArgRetSheetDTO(args={},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("noArgRetSheetDTO no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    haveArgNoRet(args={
          "title": "abc"
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("haveArgNoRet no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    haveArgRetPrimitive(args={
          "title": "abc"
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("haveArgRetPrimitive no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    haveArgRetSheetDTO(args={
          "title": "abc"
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("haveArgRetSheetDTO no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    showActionSheet(args={
          "title": "hello",
          "itemList": [
                    "hello",
                    "world",
                    "he"
          ],
          "content": "content",
          "__event__": null
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("showActionSheet no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    
}
