
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class XEMicroAppInsertDTO {
    public String appid;

    public String version;

    public String filePath;
  }
  
  interface xengine__module_microapp_i {
    public void _xxxx(final CompletionHandler<Nullable> handler);
public void _install(XEMicroAppInsertDTO dto, final CompletionHandler<Nullable> handler);
public void _clearInstallDir(XEMicroAppInsertDTO dto, final CompletionHandler<Nullable> handler);
  }
  
  
  public abstract class xengine__module_microapp extends xengine__module_BaseModule implements xengine__module_microapp_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.microapp";
    }
  
    @JavascriptInterface
    final public void xxxx(JSONObject obj, final CompletionHandler<Object> handler) {
      _xxxx(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void install(JSONObject obj, final CompletionHandler<Object> handler) {
      XEMicroAppInsertDTO data= convert(obj,XEMicroAppInsertDTO.class);
      _install(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void clearInstallDir(JSONObject obj, final CompletionHandler<Object> handler) {
      XEMicroAppInsertDTO data= convert(obj,XEMicroAppInsertDTO.class);
      _clearInstallDir(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  