
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import android.webkit.JavascriptInterface;

  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.JSIModule;


class NamedDTO {
    public String title;

    public Integer titleSize;
  }
  
  class _0_com_zkty_jsi_broadcast_DTO {
    public String type;

    public String payload;
  }
  
  interface xengine_jsi_broadcast_protocol {
    
public void _triggerBroadcast(_0_com_zkty_jsi_broadcast_DTO dto);
  }
  
  
    public abstract class xengine_jsi_broadcast extends JSIModule implements xengine_jsi_broadcast_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.broadcast";
    }
  
        @JavascriptInterface
        public Object triggerBroadcast(JSONObject jsonobj) {
          _0_com_zkty_jsi_broadcast_DTO dto= convert(jsonobj,_0_com_zkty_jsi_broadcast_DTO.class);
          _triggerBroadcast(dto);
          return null;
        }
        
  }
  

  