// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.ui", 
    [
  {
    "name": "showSuccessToast",
    "default_args": {
      "tipContent": "成功提示"
    }
  },
  {
    "name": "showFailToast",
    "default_args": {
      "tipContent": "失败提示"
    }
  },
  {
    "name": "showToast",
    "default_args": {
      "tipContent": "hello",
      "duration": 3000,
      "icon": "success"
    }
  },
  {
    "name": "hideToast",
    "default_args": {}
  },
  {
    "name": "hiddenHudToast",
    "default_args": {}
  },
  {
    "name": "showLoading",
    "default_args": {
      "tipContent": "加载提示"
    }
  },
  {
    "name": "hideLoading",
    "default_args": {}
  },
  {
    "name": "showModal",
    "default_args": {
      "tipTitle": "弹窗标题",
      "tipContent": "弹窗内容",
      "showCancel": true
    }
  },
  {
    "name": "showActionSheet",
    "default_args": {}
  },
  {
    "name": "showPickerView",
    "default_args": {}
  }
]
)}}

export default osCheck();
