
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class serviceUUIDDTO {
    public List<String> serviceUUID;
  }
  
  interface xengine__module_lope_i {
    public void _openDoor(serviceUUIDDTO dto, final CompletionHandler<Nullable> handler);
public void _customOpenDoor(final CompletionHandler<Nullable> handler);
public void _lightLift(final CompletionHandler<Nullable> handler);
public void _haveArgRetPrimitive(SheetDTO dto, final CompletionHandler<String> handler);
  }
  
  
  public abstract class xengine__module_lope extends xengine__module_BaseModule implements xengine__module_lope_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.lope";
    }
  
    @JavascriptInterface
    final public void openDoor(JSONObject obj, final CompletionHandler<Object> handler) {
      serviceUUIDDTO data= convert(obj,serviceUUIDDTO.class);
      _openDoor(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void customOpenDoor(JSONObject obj, final CompletionHandler<Object> handler) {
      _customOpenDoor(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void lightLift(JSONObject obj, final CompletionHandler<Object> handler) {
      _lightLift(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void haveArgRetPrimitive(JSONObject obj, final CompletionHandler<Object> handler) {
      SheetDTO data= convert(obj,SheetDTO.class);
      _haveArgRetPrimitive(data, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }
  }
  

  