
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  
  interface xengine__module_engine_i {
    
  }
  
  
  public abstract class xengine__module_engine extends xengine__module_BaseModule implements xengine__module_engine_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.engine";
    }
  
  }
  

  