export const SET_U = 'SET_U'

export const SET_TOPICCOUNT = 'SET_TOPICCOUNT'

export const SET_USERTOPIC = 'SET_USERTOPIC'

export const SET_USERCOLLECT = 'SET_USERCOLLECT'

export const SET_USERREPLY = 'SET_USERREPLY'

export const SET_USERREPLYFABULOUS = 'SET_USERREPLYFABULOUS'

export const SET_ACTIVE = 'SET_ACTIVE'