# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'network' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  pod 'AFNetworking', '~> 4.0.0'
 
# Pods for XEngineSDK
  pod 'x-engine-module-engine', :path =>'../../x-engine-module-engine'
  pod 'x-engine-module-protocols', :path =>'../../x-engine-module-protocols'
  pod 'x-engine-module-tools', :path =>'../../x-engine-module-tools'
#  pod 'x-engine-module-microapp', :path =>'../../x-engine-module-microapp'
# Pods for x-engine-module-newtwork
  #pod 'x-engine-module-network', :path =>'../'
 target 'networkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'networkUITests' do
    # Pods for testing
  end

end
