# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zkty-team/x-engine-pods.git'

target 'app' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  #pod 'JSONModel'
  #pod 'SSZipArchive'
  #pod 'AFNetworking'

  #pod 'DoraemonKit/Core', '~> 3.0.2', :configurations => ['Debug'] #Required
  #pod 'DoraemonKit/WithGPS', '~> 3.0.2', :configurations => ['Debug'] #Optional
  #pod 'DoraemonKit/WithLoad', '~> 3.0.2', :configurations => ['Debug'] #Optional
		
# Pods for XEngineSDK
  pod 'x-engine-module-engine'
  pod 'x-engine-module-nav'
  pod 'x-engine-module-network'
  pod 'x-engine-module-ui'
  pod 'x-engine-module-protocols'
  pod 'x-engine-module-localStorage'
  pod 'x-engine-module-camera'
  pod 'x-engine-module-offline'


  #pod 'x-engine-module-pullDownRefresh', :path =>'../../x-engine-module-pullDownRefresh'

  target 'appUITests' do
    # Pods for testing
  end

end
