
// WARNING.
// generated by api_generator.js,
// Do not modify this file. It will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class XEZipDTO {
    public String filePath;

    @Optional
		public String toZipPath;

    @Optional
		public String __event__;
  }
  
  class XEUnZipDTO {
    public String filePath;

    @Optional
		public String unZipPath;

    @Optional
		public String __event__;
  }
  
  class XEInsertDTO {
    public String appid;

    public String version;

    public String filePath;
  }
  
  interface xengine__module_tools_i {
    public void _unZipFile(XEUnZipDTO dto, final CompletionHandler<String> handler);
public void _zipFile(XEZipDTO dto, final CompletionHandler<String> handler);
  }
  
  
  public abstract class xengine__module_tools extends xengine__module_BaseModule implements xengine__module_tools_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.tools";
    }
  
    @JavascriptInterface
    public void unZipFile(JSONObject obj, final CompletionHandler<Object> handler) {
      XEUnZipDTO data= convert(obj,XEUnZipDTO.class);
      _unZipFile(data, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    public void zipFile(JSONObject obj, final CompletionHandler<Object> handler) {
      XEZipDTO data= convert(obj,XEZipDTO.class);
      _zipFile(data, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }
  }
  

  