
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

package com.zkty.jsi;
import java.util.List;
import java.util.Map;
import java.util.Set;
import android.webkit.JavascriptInterface;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.zkty.nativ.jsi.bridge.CompletionHandler;
import com.zkty.nativ.jsi.JSIModule;
import androidx.annotation.Nullable;
import com.zkty.nativ.core.annotation.Optional;


class _0_com_zkty_jsi_browser_DTO {
  public Integer code;

    public String msg;
  }
  
class _1_com_zkty_jsi_browser_DTO {
  public String url;
  }

interface xengine_jsi_browser_protocol {
  public void _open(_1_com_zkty_jsi_browser_DTO dto, final CompletionHandler<_0_com_zkty_jsi_browser_DTO> handler);
}
  

    public abstract class xengine_jsi_browser extends JSIModule implements xengine_jsi_browser_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.browser";
    }
  
    @JavascriptInterface
    final public void open(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _1_com_zkty_jsi_browser_DTO dto= convert(jsonobj,_1_com_zkty_jsi_browser_DTO.class);
      _open(dto, new CompletionHandler<_0_com_zkty_jsi_browser_DTO>() {
        @Override
        public void complete(_0_com_zkty_jsi_browser_DTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(_0_com_zkty_jsi_browser_DTO value) { handler.setProgressData(value); }
      });

    }
  }
  

  