push-to-pods:
	pod repo push x-engine-pods x-engine-module-*.podspec --use-libraries --sources='https://github.com/CocoaPods/Specs.git,https://github.com/zkty-team/x-engine-pods.git'  --allow-warnings

push:
	pod repo push x-engine-pods x-engine-module-app.podspec --use-libraries   --allow-warnings
