# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
source 'https://github.com/CocoaPods/Specs.git'

X_ENGINE_ROOT=ENV['X_ENGINE_ROOT'] || '../..'

def shared_pods
  pod 'x-engine-native-core', :path =>X_ENGINE_ROOT+'/modules/x-engine-native-core'
  pod 'x-engine-native-jsi', :path =>X_ENGINE_ROOT+'/modules/x-engine-native-jsi'
  pod 'x-engine-native-direct_omp', :path =>X_ENGINE_ROOT+'/modules/x-engine-native-direct_omp'
  pod 'x-engine-native-direct_microapp', :path =>X_ENGINE_ROOT+'/modules/x-engine-native-direct_microapp'

  pod 'x-engine-native-protocols', :path =>X_ENGINE_ROOT+'/modules/x-engine-native-protocols'
  pod 'x-engine-native-direct', :path =>X_ENGINE_ROOT+'/modules/x-engine-native-direct'

end

target 'xxxx' do
  #use_frameworks!
  shared_pods
end
target 'xxxxTests' do
  #use_frameworks!
  shared_pods
end
target 'xxxxUITests' do
  # Pods for testing
  shared_pods

end
