
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.modules.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;

  
  class RouterOpenAppDTO {
    public String type;

    public String uri;

    public String path;

    @Optional
		public Map<String,String> args;

    @Optional
		public Integer version;

    @Optional
		public boolean hideNavbar;
  }
  
  interface xengine_module_router_protocol {
    public void _openTargetRouter(RouterOpenAppDTO dto, final CompletionHandler<Nullable> handler);
  }
  
  
  public abstract class xengine_module_router extends JSIModule implements xengine_module_router_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.module.router";
    }
  
    @JavascriptInterface
    final public void openTargetRouter(JSONObject obj, final CompletionHandler<Object> handler) {
      RouterOpenAppDTO data= convert(obj,RouterOpenAppDTO.class);
      _openTargetRouter(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  