
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

package com.zkty.jsi;
import java.util.List;
import java.util.Map;
import java.util.Set;
import android.webkit.JavascriptInterface;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.zkty.nativ.jsi.bridge.CompletionHandler;
import com.zkty.nativ.jsi.JSIModule;
import androidx.annotation.Nullable;
import com.zkty.nativ.core.annotation.Optional;


class PostReq {
  public String userId;

    @Optional
		public Integer tid;

    public String title;

    public boolean completed;

    public String message;

    public String moreMsg;
  }
  
class PostRes {
  public Map<String,String> args;

    public String data;

    public Map<String,String> files;

    public Map<String,String> form;

    public Map<String,String> headers;

    public Map<String,String> json;

    public String origin;

    public String url;
  }

interface undefined_protocol {
  
}
  

    public abstract class undefined extends JSIModule implements undefined_protocol {
    @Override
    public String moduleId() {
      return "undefined";
    }
  
  }
  

  