// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.nav", 
    [
  {
    "name": "setNavTitle",
    "default_args": null
  },
  {
    "name": "setNavLeftBtn",
    "default_args": null
  },
  {
    "name": "setNavRightBtn",
    "default_args": null
  },
  {
    "name": "setNavRightMenuBtn",
    "default_args": null
  },
  {
    "name": "setNavRightMoreBtn",
    "default_args": null
  },
  {
    "name": "navigatorPush",
    "default_args": {}
  },
  {
    "name": "navigatorBack",
    "default_args": {}
  },
  {
    "name": "setNavSearchBar",
    "default_args": null
  },
  {
    "name": "setSearchBarHidden",
    "default_args": null
  },
  {
    "name": "setNavBarHidden",
    "default_args": null
  },
  {
    "name": "removeHistoryPage",
    "default_args": null
  }
]
)}}

export default osCheck();
