
// MODIFIALBE! 
// generated by x-cli,
// only generated when file is not existed!

export default {

    
    setNavTitle(args={
          "title": "title",
          "titleColor": "#000000",
          "titleSize": 16
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("setNavTitle no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    setNavLeftBtn(args={
          "title": "left",
          "titleColor": "#000000",
          "titleSize": 16,
          "icon": "",
          "iconSize": [
                    "20",
                    "20"
          ]
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("setNavLeftBtn no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    setNavRightBtn(args={
          "title": "right",
          "titleColor": "#000000",
          "titleSize": 16,
          "icon": "",
          "iconSize": [
                    "20",
                    "20"
          ]
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("setNavRightBtn no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    setNavRightMenuBtn(args={
          "title": "menu",
          "titleColor": "#000000",
          "titleSize": 16,
          "icon": "",
          "iconSize": [
                    "20",
                    "20"
          ],
          "popWidth": "200",
          "showMenuImg": "false",
          "popList": [
                    {
                              "icon": "",
                              "iconSize": "20",
                              "title": "1"
                    },
                    {
                              "icon": "",
                              "iconSize": "20",
                              "title": "2"
                    },
                    {
                              "icon": "",
                              "iconSize": "20",
                              "title": "3"
                    }
          ]
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("setNavRightMenuBtn no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    setNavRightMoreBtn(args={
          "btns": [
                    {
                              "title": "right1",
                              "titleColor": "#000000",
                              "titleSize": 16,
                              "iconSize": [
                                        "20",
                                        "20"
                              ]
                    },
                    {
                              "title": "",
                              "icon": "/assets/search.png",
                              "titleColor": "#000000",
                              "titleSize": 16,
                              "iconSize": [
                                        "20",
                                        "20"
                              ]
                    }
          ]
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("setNavRightMoreBtn no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    navigatorPush(args={
          "url": ""
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("navigatorPush no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    navigatorBack(args={
          "url": ""
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("navigatorBack no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    setNavSearchBar(args={
          "cornerRadius": 5,
          "backgroundColor": "#FF0000",
          "iconSearch": "",
          "iconSearchSize": [
                    20,
                    20
          ],
          "iconClear": "",
          "iconClearSize": [
                    20,
                    20
          ],
          "textColor": "#000000",
          "fontSize": 16,
          "placeHolder": "默认文字",
          "placeHolderFontSize": 16,
          "isInput": true,
          "becomeFirstResponder": false
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("setNavSearchBar no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    
}
