
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class WalletDTO {
    public String platMerCstNo;

    public String businessCstName;

    public String businessCstNo;

    public String businessCstMobileNo;

    @Optional
		public String appScheme;
  }
  
  interface xengine__module_wallet_i {
    public void _callWallet(WalletDTO dto, final CompletionHandler<Nullable> handler);
  }
  
  
  public abstract class xengine__module_wallet extends xengine__module_BaseModule implements xengine__module_wallet_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.wallet";
    }
  
    @JavascriptInterface
    final public void callWallet(JSONObject obj, final CompletionHandler<Object> handler) {
      WalletDTO data= convert(obj,WalletDTO.class);
      _callWallet(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  