// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-core";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.store", 
    [
  {
    "name": "test_setObject",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getObject",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_setObject_sync",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getObject_sync",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_setNil",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getNil",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_setAssertChangeColor",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getAssertTrue",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
