// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-core";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.localstorage", 
    [
  {
    "name": "test_set_abc_world",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_get",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
