// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.demo", 
    [
  {
    "name": "noArgNoRet",
    "default_args": {}
  },
  {
    "name": "noArgRetPrimitive",
    "default_args": {}
  },
  {
    "name": "noArgRetSheetDTO",
    "default_args": {}
  },
  {
    "name": "haveArgNoRet",
    "default_args": {
      "title": "abc"
    }
  },
  {
    "name": "haveArgRetPrimitive",
    "default_args": {
      "title": "abc"
    }
  },
  {
    "name": "haveArgRetSheetDTO",
    "default_args": {
      "title": "abc"
    }
  },
  {
    "name": "showActionSheet",
    "default_args": {
      "title": "hello",
      "itemList": [
        "hello",
        "world",
        "he"
      ],
      "content": "content",
      "__event__": null
    }
  }
]
)}}

export default osCheck();
