
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import android.webkit.JavascriptInterface;

import androidx.annotation.Nullable;

import com.alibaba.fastjson.JSONObject;
import com.zkty.nativ.core.annotation.Optional;
import com.zkty.nativ.jsi.JSIModule;
import com.zkty.nativ.jsi.bridge.CompletionHandler;

import java.util.List;

  
  class OpenShareUiDTO {
    @Optional
		public String shopWechatGroupImgUrl;

    public List<ChannelDTO> channelList;
  }
  
  class ChannelDTO {
    public String channel;

    public String shareType;
  }
  
  class ChannelStatusDTO {
    public String channel;

    public String shareType;

    @Optional
		public String shareImgData;
  }
  
  class PosterDTO {
    public String posterType;

    public String posterImgUrl;

    @Optional
		public String shopLogoUrl;

    @Optional
		public String shopName;

    @Optional
		public String shopAddress;

    @Optional
		public String rightCornerImg;

    @Optional
		public String minProgramImg;

    @Optional
		public String goodsTitle;

    @Optional
		public String goodsPrice;

    @Optional
		public String activityName;
  }
  
  interface xengine_jsi_gmshare_protocol {
    public void _openShareUi(OpenShareUiDTO dto, final CompletionHandler<ChannelStatusDTO> handler);
public void _createPoster(PosterDTO dto, final CompletionHandler<Nullable> handler);
  }
  
  
    public abstract class xengine_jsi_gmshare extends JSIModule implements xengine_jsi_gmshare_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.gmshare";
    }
  
    @JavascriptInterface
    final public void openShareUi(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      OpenShareUiDTO dto= convert(jsonobj,OpenShareUiDTO.class);
      _openShareUi(dto, new CompletionHandler<ChannelStatusDTO>() {
        @Override
        public void complete(ChannelStatusDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(ChannelStatusDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void createPoster(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      PosterDTO dto= convert(jsonobj,PosterDTO.class);
      _createPoster(dto, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  