
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.core.annotation.Optional;

  
  class OpenShareUiDTO {
    @Optional
		public String shopWechatGroupImgUrl;

    public List<ChannelDTO> channelList;
  }
  
  class ChannelDTO {
    public String channel;

    public String shareType;
  }
  
  class ChannelStatusDTO {
    public String channel;

    public String shareType;

    @Optional
		public String shareImgData;
  }
  
  class PosterDTO {
    public String posterType;

    public String posterImgUrl;

    @Optional
		public String shopLogoUrl;

    @Optional
		public String shopName;

    @Optional
		public String shopAddress;

    @Optional
		public String rightCornerImg;

    @Optional
		public String minProgramImg;

    @Optional
		public String goodsTitle;

    @Optional
		public String goodsPrice;

    @Optional
		public String activityName;
  }
  
  interface xengine_jsi_gmshare_protocol {
    public void _openShareUi(OpenShareUiDTO dto, final CompletionHandler<ChannelStatusDTO> handler);

public void _createPoster(PosterDTO dto);
  }
  
  
    public abstract class xengine_jsi_gmshare extends JSIModule implements xengine_jsi_gmshare_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.gmshare";
    }
  
    @JavascriptInterface
    final public void openShareUi(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      OpenShareUiDTO dto= convert(jsonobj,OpenShareUiDTO.class);
      _openShareUi(dto, new CompletionHandler<ChannelStatusDTO>() {
        @Override
        public void complete(ChannelStatusDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(ChannelStatusDTO value) { handler.setProgressData(value); }
      });

    }

        @JavascriptInterface
        public Object createPoster(JSONObject jsonobj) {
          PosterDTO dto= convert(jsonobj,PosterDTO.class);
          _createPoster(dto);
          return null;
        }
        
  }
  

  