
// MODIFIALBE! 
// generated by x-cli,
// only generated when file is not existed!

export default {

    
    unZipFile(args={
          "filePath": "",
          "unZipPath": ""
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("unZipFile no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    zipFile(args={
          "filePath": "",
          "toZipPath": ""
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("zipFile no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    
}
