
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

package com.zkty.jsi;
import java.util.List;
import java.util.Map;
import java.util.Set;
import android.webkit.JavascriptInterface;
import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.zkty.nativ.jsi.bridge.CompletionHandler;
import com.zkty.nativ.jsi.JSIModule;
import androidx.annotation.Nullable;
import com.zkty.nativ.core.annotation.Optional;


class NamedDTO {
  public String title;

    public Integer titleSize;
  }
  
class _0_com_zkty_jsi_enviroment_DTO {
  public Integer code;

    public String msg;
  }

interface xengine_jsi_enviroment_protocol {
  
public _0_com_zkty_jsi_enviroment_DTO _isHybird();
}
  

    public abstract class xengine_jsi_enviroment extends JSIModule implements xengine_jsi_enviroment_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.enviroment";
    }
  
        @JavascriptInterface
        public _0_com_zkty_jsi_enviroment_DTO isHybird(JSONObject jsonobj) {
          
          return _isHybird();
        }
        
  }
  

  