
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.jsapi.jsapi;

  import com.zkty.modules.engine.core.xengine__module_BaseModule;


interface xengine__module_engine_i {
    
  }
  
  
  public abstract class xengine__module_engine extends xengine__module_BaseModule implements xengine__module_engine_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.engine";
    }
  
  }
  

  