// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-core";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.media", 
    [
  {
    "name": "test_placeholder",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_placeholder",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_placeholder",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_openImagePicker",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_saveImageToPhotoAlbum",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
