// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.tzcash", 
    [
  {
    "name": "callPaymentSDK",
    "default_args": {
      "orderNoList": "8448617924972777512",
      "businessCstNo": "15374649080",
      "platMerCstNo": "8377631273379692750",
      "frontBackUrl": "123"
    }
  }
]
)}}

export default osCheck();
