
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.core.annotation.Optional;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;

  
  class ShareDTO {
    public String channel;

    public String type;

    public Map<String,String> info;
  }
  
  class ShareTextDTO {
    public String text;
  }
  
  class ShareImgDTO {
    public String imgData;
  }
  
  class ShareLinkDTO {
    public String title;

    public String desc;

    @Optional
		public String imgUrl;

    public String url;
  }
  
  class ShareMiniProgramDTO {
    public String userName;

    public String path;

    public String link;

    public Integer miniProgramType;

    public String title;

    public String desc;

    public String imgUrl;
  }
  
  interface xengine_jsi_share_protocol {
    public void _share(ShareDTO dto, final CompletionHandler<Nullable> handler);
  }
  
  
    public abstract class xengine_jsi_share extends JSIModule implements xengine_jsi_share_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.share";
    }
  
    @JavascriptInterface
    final public void share(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      ShareDTO dto= convert(jsonobj,ShareDTO.class);
      _share(dto, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  