
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.jsi.annotation.Optional;

  
  class _0_com_zkty_jsi_share_DTO {
    public String channel;

    public String type;

    @Optional
		public String title;

    @Optional
		public String desc;

    @Optional
		public String text;

    @Optional
		public String imgUrl;

    @Optional
		public String imgData;

    @Optional
		public String url;

    @Optional
		public String userName;

    @Optional
		public String path;

    @Optional
		public String link;

    @Optional
		public Integer miniProgramType;
  }
  
  interface xengine_jsi_share_protocol {
    public void _share(_0_com_zkty_jsi_share_DTO dto, final CompletionHandler<String> handler);
  }
  
  
    public abstract class xengine_jsi_share extends JSIModule implements xengine_jsi_share_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.share";
    }
  
    @JavascriptInterface
    final public void share(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _0_com_zkty_jsi_share_DTO dto= convert(jsonobj,_0_com_zkty_jsi_share_DTO.class);
      _share(dto, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }
  }
  

  