
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.core.annotation.Optional;

  
  class NamedDTO {
    public String title;

    public Integer titleSize;
  }
  
  interface xengine_jsi_webcache_protocol {
    public void _simpleMethod(final CompletionHandler<Nullable> handler);
public void _simpleMethod();
  }
  
  
    public abstract class xengine_jsi_webcache extends JSIModule implements xengine_jsi_webcache_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.webcache";
    }
  
    @JavascriptInterface
    final public void simpleMethod(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _simpleMethod(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
        @JavascriptInterface
        public Object simpleMethod(JSONObject jsonobj) {
          
          _simpleMethod();
          return null;
        }
        
  }
  

  