// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-core";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.broadcast", 
    [
  {
    "name": "test_triggerNativeBroadcastNull",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_ontriggerNativeBroadcastNull",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_triggerbroadcast",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_onbroadcast",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_triggerbroadcast_null",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_onbroadcast_null",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
