// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.localstorage", 
    [
  {
    "name": "setLocalStorage",
    "default_args": {
      "key": "key",
      "value": "value",
      "isPublic": false
    }
  },
  {
    "name": "getLocalStorage",
    "default_args": {
      "key": "key",
      "isPublic": false
    }
  },
  {
    "name": "removeLocalStorageItem",
    "default_args": {
      "key": "item",
      "isPublic": false
    }
  },
  {
    "name": "removeLocalStorageAll",
    "default_args": {
      "key": "all",
      "isPublic": false
    }
  },
  {
    "name": "_testSetOtherIDLocalStorage",
    "default_args": {
      "key": "key",
      "value": "value",
      "isPublic": false
    }
  },
  {
    "name": "_testGetOtherIDLocalStorage",
    "default_args": {
      "key": "key",
      "isPublic": false
    }
  }
]
)}}

export default osCheck();
