// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.localstorage", 
    [
  {
    "name": "set",
    "default_args": null
  },
  {
    "name": "get",
    "default_args": null
  },
  {
    "name": "remove",
    "default_args": null
  },
  {
    "name": "removeAll",
    "default_args": null
  },
  {
    "name": "_testRemoveAllPublic",
    "default_args": null
  },
  {
    "name": "_testSetPublicStorage",
    "default_args": {}
  },
  {
    "name": "_testGetPublicStorage",
    "default_args": {}
  },
  {
    "name": "_testSetLocalStorage",
    "default_args": {}
  },
  {
    "name": "_testGetLocalStorage",
    "default_args": {}
  }
]
)}}

export default osCheck();
