@startuml
!define DARKGREEN
!includeurl http://md4zk.oss-cn-beijing.aliyuncs.com/files/style1.puml
skinparam componentStyle uml2
skinparam packageStyle rectangle
 
 class Demo {
    - private
    ....
    # protected
    --
    + public
    .. 描述 ..
    + public 
        
    ~ hello()

 }
note left: 这是注释
Demo <-left- Myclass
Demo <-right- Myclass2
Demo <|-- Myclass3
Demo <|.... LongMyclass4
Demo <|.. ShortMyclass4
Demo <|....... SuperLongMyclass4


 

@enduml
