// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.ui", 
    [
  {
    "name": "setNavTitle",
    "default_args": {
      "titleColor": "#000000",
      "titleSize": 16
    },
    "decorators": []
  },
  {
    "name": "setNavBarHidden",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
