
// MODIFIALBE! 
// generated by x-cli,
// only generated when file is not existed!

export default {

    
    setLocalStorage(args={
          "key": "key",
          "value": "value",
          "isPublic": false
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("setLocalStorage no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    getLocalStorage(args={
          "key": "key",
          "isPublic": false
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("getLocalStorage no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    removeLocalStorageItem(args={
          "key": "item",
          "isPublic": false
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("removeLocalStorageItem no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    removeLocalStorageAll(args={
          "key": "all",
          "isPublic": false
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("removeLocalStorageAll no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    _testSetOtherIDLocalStorage(args={
          "key": "key",
          "value": "value",
          "isPublic": false
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("_testSetOtherIDLocalStorage no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    _testGetOtherIDLocalStorage(args={
          "key": "key",
          "isPublic": false
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("_testGetOtherIDLocalStorage no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    
}
