// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.dcloud", 
    [
  {
    "name": "openUniMP",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "preloadUniMP",
    "default_args": {
      "showAnimated": true,
      "hideAnimated": true
    },
    "decorators": []
  },
  {
    "name": "openUniMPWithArg",
    "default_args": {
      "showAnimated": true,
      "hideAnimated": true
    },
    "decorators": []
  }
]
)}}

export default osCheck();
