// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.dcloud", 
    [
  {
    "name": "openUniMP",
    "default_args": null
  },
  {
    "name": "preloadUniMP",
    "default_args": {
      "enableBackground": false
    }
  },
  {
    "name": "openUniMPWithArg",
    "default_args": {
      "enableBackground": false
    }
  }
]
)}}

export default osCheck();
