// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.dcloud", 
    [
  {
    "name": "openUniMP",
    "default_args": {
      "appId": "__UNI__11E9B73"
    }
  },
  {
    "name": "preloadUniMP",
    "default_args": {
      "appId": "__UNI__11E9B73",
      "arguments": {
        "token": "this is token",
        "refreshtoken": "this is refreshtoken"
      },
      "redirectPath": "pages/component/application/application?token=a&refreshtoken=b",
      "enableBackground": false
    }
  },
  {
    "name": "openUniMPWithArg",
    "default_args": {
      "appId": "__UNI__9B75743",
      "arguments": {
        "token": "this is token",
        "refreshtoken": "this is refreshtoken"
      },
      "redirectPath": "pages/component/application/application?token=a&refreshtoken=b",
      "enableBackground": false
    }
  }
]
)}}

export default osCheck();
