
// MODIFIALBE! 
// generated by api_generator.js,
// only generated when file is not existed!

export default {

    
    openUniMP(args={
          "appId": "__UNI__5DE1E68"
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("openUniMP no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    preloadUniMP(args={
          "appId": "__UNI__11E9B73"
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("preloadUniMP no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    ,
    
    openUniMPWithArg(args={
          "appId": "__UNI__11E9B73",
          "arguments": {
                    "arguments": "Hello uni microprogram"
          },
          "redirectPath": "pages/component/view/view",
          "enableBackground": false
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("openUniMPWithArg no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    
}
