// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.direct_manager", 
    [
  {
    "name": "push",
    "default_args": {
      "scheme": "h5",
      "pathname": "/",
      "params": {
        "hideNavbar": true
      }
    },
    "decorators": []
  },
  {
    "name": "back",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
