
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;

  import android.webkit.JavascriptInterface;

  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.core.annotation.Optional;

  
  class SheetDTO {
    public String title;

    @Optional
		public List<String> itemList;

    @Optional
		public String content;

    public String __event__;
  }
  
  class ContinousDTO {
    @Optional
		public String __event__;
  }
  
  class MsgPayloadDTO {
    public String type;

    @Optional
		public Map<String,String> args;

    @Optional
		public String sender;

    @Optional
		public List<String> receiver;

    public String __event__;

    public String __ret__;
  }
  
  interface xengine_jsi_legacy_protocol {
    public void _broadcastOn(final CompletionHandler<Nullable> handler);
public void _broadcastOff(final CompletionHandler<Nullable> handler);
public void _triggerNativeBroadCast(final CompletionHandler<Nullable> handler);
public void _repeatReturn__event__(ContinousDTO dto, final CompletionHandler<String> handler);
public void _repeatReturn__ret__(ContinousDTO dto, final CompletionHandler<String> handler);
public void _ReturnInPromiseThen(ContinousDTO dto, final CompletionHandler<String> handler);
  }
  
  
  public abstract class xengine_jsi_legacy extends JSIModule implements xengine_jsi_legacy_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.legacy";
    }
  
    @JavascriptInterface
    final public void broadcastOn(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _broadcastOn(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void broadcastOff(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _broadcastOff(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void triggerNativeBroadCast(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _triggerNativeBroadCast(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void repeatReturn__event__(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      ContinousDTO dto= convert(jsonobj,ContinousDTO.class);
      _repeatReturn__event__(dto, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void repeatReturn__ret__(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      ContinousDTO dto= convert(jsonobj,ContinousDTO.class);
      _repeatReturn__ret__(dto, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void ReturnInPromiseThen(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      ContinousDTO dto= convert(jsonobj,ContinousDTO.class);
      _ReturnInPromiseThen(dto, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }
  }
  

  