// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.container", 
    [
  {
    "name": "push",
    "default_args": {
      "direction": 0
    }
  }
]
)}}

export default osCheck();
