
// MODIFIALBE! 
// generated by x-cli,
// only generated when file is not existed!

export default {

    
    push(args={
          "direction": 0
},userPromise){
      if(userPromise){
        return userPromise()
      }else{
        return new Promise((resolve, reject)=>{
          alert("push no h5 implementation, you can implement this function in mock.js in  h5/src/mock.js");
          resolve(null);
        });
      }

    }
    
}
