
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.modules.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;

  
  class GeoEventDTO {
    public String type;

    @Optional
		public String __event__;
  }
  
  class GeoLocationResDTO {
    public String longitude;

    public String latitude;

    public String country;

    public String province;

    public String city;

    public String district;

    public String town;

    public String street;
  }
  
  interface xengine_module_geo_protocol {
    public void _locate(GeoEventDTO dto, final CompletionHandler<Nullable> handler);
  }
  
  
  public abstract class xengine_module_geo extends JSIModule implements xengine_module_geo_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.module.geo";
    }
  
    @JavascriptInterface
    final public void locate(JSONObject obj, final CompletionHandler<Object> handler) {
      GeoEventDTO data= convert(obj,GeoEventDTO.class);
      _locate(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  