# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/zkty-team/x-engine-pods.git'

target 'ModuleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  #pod 'JSONModel'
  #pod 'SSZipArchive'
  #pod 'AFNetworking'
  #pod 'XEngineSDK'
  #pod 'UIModule'
		
 
# Pods for XEngineSDK
  pod 'x-engine-module-engine', :path =>'../../x-engine-module-engine'
  #pod 'x-engine-module-microapp', :path =>'../../x-engine-module-microapp'
  pod 'x-engine-module-tools', :path =>'../../x-engine-module-tools'
  pod 'x-engine-module-protocols', :path =>'../../x-engine-module-protocols/'

  

 target 'ModuleAppTests' do
    # Pods for testing
  end

  target 'ModuleAppUITests' do
    # Pods for testing
  end

end
