require_relative '../node_modules/react-native/scripts/react_native_pods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/zkty-team/x-engine-pods.git'

target 'rn' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'AFNetworking', '~> 4.0.0'

end
