
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.jsi.annotation.Optional;

  
  class OpenFiileDTO {
    public String filePath;

    public String fileName;
  }
  
  class StatusDTO {
    public String result;
  }
  
  interface xengine_jsi_viewer_protocol {
    public void _openFileReader(OpenFiileDTO dto, final CompletionHandler<StatusDTO> handler);
  }
  
  
  public abstract class xengine_jsi_viewer extends JSIModule implements xengine_jsi_viewer_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.viewer";
    }
  
    @JavascriptInterface
    final public void openFileReader(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      OpenFiileDTO dto= convert(jsonobj,OpenFiileDTO.class);
      _openFileReader(dto, new CompletionHandler<StatusDTO>() {
        @Override
        public void complete(StatusDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(StatusDTO value) { handler.setProgressData(value); }
      });

    }
  }
  

  