// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-core";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.device", 
    [
  {
    "name": "test_getStatusHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getNavHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getScreenHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getTabbarHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_callPhone",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_sendMsg",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getDeviceInfo",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_getDeviceInfo1",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
