// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-core";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.device", 
    [
  {
    "name": "getStatusBarHeight",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "getNavigationHeight",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "getScreenHeight",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "getTabbarHeight",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "getSystemVersion",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "getUUID",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "callPhone",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "sendMessage",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "getDeviceInfo",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "getDeviceInfo1",
    "default_args": {},
    "decorators": [
      "async"
    ]
  },
  {
    "name": "text_getScreenHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "text_getTabbarHeight",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "text_callPhone",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "text_sendMsg",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "text_getDeviceInfo",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "text_getDeviceInfo1",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
