# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
source 'https://github.com/CocoaPods/Specs.git'

#load './ModulePods.rb'
abstract_target 'abstract' do
  pod 'x-engine-module-engine', :path =>'../../x-engine-module-engine'
  pod 'x-engine-module-tools', :path =>'../../x-engine-module-tools/'
  pod 'x-engine-module-protocols', :path =>'../../x-engine-module-protocols/'
  target 'yjzdbill' do
    #use_frameworks!
    #module_pods
  end
  target 'yjzdbillTests' do
    #use_frameworks!
    #module_pods
  end
  target 'yjzdbillUITests' do
    # Pods for testing
  end
end
