
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.jsi.annotation.Optional;

  
  class phoneDto {
    public String phoneNum;

    public String phoneMsg;
  }
  
  class DeviceDTO {
    public String type;

    public String systemVersion;

    public String language;

    public String UUID;
  }
  
  interface xengine_jsi_device_protocol {
    
public String _getStatusBarHeight();

public String _getNavigationHeight();

public String _getScreenHeight();

public String _getTabbarHeight();

public String _callPhone(phoneDto dto);

public String _sendMessage(phoneDto dto);
public void _getDeviceInfo(final CompletionHandler<DeviceDTO> handler);
  }
  
  
    public abstract class xengine_jsi_device extends JSIModule implements xengine_jsi_device_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.device";
    }
  
        @JavascriptInterface
        public String getStatusBarHeight(JSONObject jsonobj) {
          
          return _getStatusBarHeight();
        }
        

        @JavascriptInterface
        public String getNavigationHeight(JSONObject jsonobj) {
          
          return _getNavigationHeight();
        }
        

        @JavascriptInterface
        public String getScreenHeight(JSONObject jsonobj) {
          
          return _getScreenHeight();
        }
        

        @JavascriptInterface
        public String getTabbarHeight(JSONObject jsonobj) {
          
          return _getTabbarHeight();
        }
        

        @JavascriptInterface
        public String callPhone(JSONObject jsonobj) {
          phoneDto dto= convert(jsonobj,phoneDto.class);
          return _callPhone(dto);
        }
        

        @JavascriptInterface
        public String sendMessage(JSONObject jsonobj) {
          phoneDto dto= convert(jsonobj,phoneDto.class);
          return _sendMessage(dto);
        }
        

    @JavascriptInterface
    final public void getDeviceInfo(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _getDeviceInfo(new CompletionHandler<DeviceDTO>() {
        @Override
        public void complete(DeviceDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(DeviceDTO value) { handler.setProgressData(value); }
      });

    }
  }
  

  