
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.modules.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;

  
  class phoneDto {
    public String phoneNum;

    public String phoneMsg;
  }
  
  class DeviceDTO {
    public String type;

    public String systemVersion;

    public String language;

    public String UUID;
  }
  
  interface xengine_jsi_device_protocol {
        String _getStatusBarHeight();
    String _getNavigationHeight();
    String _getScreenHeight();
    String _getTabbarHeight();
    String _getSystemVersion();
    String _getUUID();
    String _callPhone(phoneDto dto);
    String _sendMessage(phoneDto dto);
    String _getDeviceInfo();
public void _getDeviceInfo1(final CompletionHandler<DeviceDTO> handler);
public void _text_getScreenHeight(final CompletionHandler<Nullable> handler);
public void _text_getTabbarHeight(final CompletionHandler<Nullable> handler);
public void _text_callPhone(final CompletionHandler<Nullable> handler);
public void _text_sendMsg(final CompletionHandler<Nullable> handler);
public void _text_getDeviceInfo(final CompletionHandler<Nullable> handler);
public void _text_getDeviceInfo1(final CompletionHandler<Nullable> handler);
  }
  
  
  public abstract class xengine_jsi_device extends JSIModule implements xengine_jsi_device_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.device";
    }
  
        @JavascriptInterface
        public String getStatusBarHeight(JSONObject jsonobj) {
          
          return _getStatusBarHeight();
        }
        

        @JavascriptInterface
        public String getNavigationHeight(JSONObject jsonobj) {
          
          return _getNavigationHeight();
        }
        

        @JavascriptInterface
        public String getScreenHeight(JSONObject jsonobj) {
          
          return _getScreenHeight();
        }
        

        @JavascriptInterface
        public String getTabbarHeight(JSONObject jsonobj) {
          
          return _getTabbarHeight();
        }
        

        @JavascriptInterface
        public String getSystemVersion(JSONObject jsonobj) {
          
          return _getSystemVersion();
        }
        

        @JavascriptInterface
        public String getUUID(JSONObject jsonobj) {
          
          return _getUUID();
        }
        

        @JavascriptInterface
        public String callPhone(JSONObject jsonobj) {
          phoneDto data= convert(obj,phoneDto.class);
          return _callPhone(dto);
        }
        

        @JavascriptInterface
        public String sendMessage(JSONObject jsonobj) {
          phoneDto data= convert(obj,phoneDto.class);
          return _sendMessage(dto);
        }
        

        @JavascriptInterface
        public String getDeviceInfo(JSONObject jsonobj) {
          
          return _getDeviceInfo();
        }
        

    @JavascriptInterface
    final public void getDeviceInfo1(JSONObject obj, final CompletionHandler<Object> handler) {
      _getDeviceInfo1(new CompletionHandler<DeviceDTO>() {
        @Override
        public void complete(DeviceDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(DeviceDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void text_getScreenHeight(JSONObject obj, final CompletionHandler<Object> handler) {
      _text_getScreenHeight(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void text_getTabbarHeight(JSONObject obj, final CompletionHandler<Object> handler) {
      _text_getTabbarHeight(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void text_callPhone(JSONObject obj, final CompletionHandler<Object> handler) {
      _text_callPhone(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void text_sendMsg(JSONObject obj, final CompletionHandler<Object> handler) {
      _text_sendMsg(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void text_getDeviceInfo(JSONObject obj, final CompletionHandler<Object> handler) {
      _text_getDeviceInfo(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void text_getDeviceInfo1(JSONObject obj, final CompletionHandler<Object> handler) {
      _text_getDeviceInfo1(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  