
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.modules.loaded.jsapi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.dsbridge.CompletionHandler;
  import com.zkty.modules.engine.annotation.Optional;
  import com.zkty.modules.engine.core.xengine__module_BaseModule;
  import androidx.annotation.Nullable;

  
  class BuletoothEventDTO {
    public String __event__;
  }
  
  class BuletoothContentDTO {
    public String content;
  }
  
  class BuletoothDeviceDTO {
    public String deviceID;

    public String __event__;
  }
  
  class BtCharacteristicsDTO {
    public String deviceID;

    public String serviceId;

    public String __event__;
  }
  
  class BtCharacteristicIdDTO {
    public String characteristicId;

    public String __event__;
  }
  
  interface xengine__module_bluetooth_i {
    public void _initBluetooth(BuletoothEventDTO dto, final CompletionHandler<BuletoothContentDTO> handler);
public void _scanBluetoothDevice(BuletoothEventDTO dto, final CompletionHandler<BuletoothContentDTO> handler);
public void _closeBluetoothDevice(final CompletionHandler<Nullable> handler);
public void _linkBluetoothDevice(BuletoothDeviceDTO dto, final CompletionHandler<BuletoothContentDTO> handler);
public void _cancelLinkBluetoothDevice(BuletoothDeviceDTO dto, final CompletionHandler<BuletoothContentDTO> handler);
public void _discoverServices(BuletoothDeviceDTO dto, final CompletionHandler<BuletoothContentDTO> handler);
public void _discoverCharacteristics(BtCharacteristicsDTO dto, final CompletionHandler<BuletoothContentDTO> handler);
public void _writeValueForCharacteristic(BtCharacteristicIdDTO dto, final CompletionHandler<BuletoothContentDTO> handler);
public void _readCharacteristic(BtCharacteristicIdDTO dto, final CompletionHandler<BuletoothContentDTO> handler);
  }
  
  
  public abstract class xengine__module_bluetooth extends xengine__module_BaseModule implements xengine__module_bluetooth_i {
    @Override
    public String moduleId() {
      return "com.zkty.module.bluetooth";
    }
  
    @JavascriptInterface
    final public void initBluetooth(JSONObject obj, final CompletionHandler<Object> handler) {
      BuletoothEventDTO data= convert(obj,BuletoothEventDTO.class);
      _initBluetooth(data, new CompletionHandler<BuletoothContentDTO>() {
        @Override
        public void complete(BuletoothContentDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(BuletoothContentDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void scanBluetoothDevice(JSONObject obj, final CompletionHandler<Object> handler) {
      BuletoothEventDTO data= convert(obj,BuletoothEventDTO.class);
      _scanBluetoothDevice(data, new CompletionHandler<BuletoothContentDTO>() {
        @Override
        public void complete(BuletoothContentDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(BuletoothContentDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void closeBluetoothDevice(JSONObject obj, final CompletionHandler<Object> handler) {
      _closeBluetoothDevice(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }

    @JavascriptInterface
    final public void linkBluetoothDevice(JSONObject obj, final CompletionHandler<Object> handler) {
      BuletoothDeviceDTO data= convert(obj,BuletoothDeviceDTO.class);
      _linkBluetoothDevice(data, new CompletionHandler<BuletoothContentDTO>() {
        @Override
        public void complete(BuletoothContentDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(BuletoothContentDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void cancelLinkBluetoothDevice(JSONObject obj, final CompletionHandler<Object> handler) {
      BuletoothDeviceDTO data= convert(obj,BuletoothDeviceDTO.class);
      _cancelLinkBluetoothDevice(data, new CompletionHandler<BuletoothContentDTO>() {
        @Override
        public void complete(BuletoothContentDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(BuletoothContentDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void discoverServices(JSONObject obj, final CompletionHandler<Object> handler) {
      BuletoothDeviceDTO data= convert(obj,BuletoothDeviceDTO.class);
      _discoverServices(data, new CompletionHandler<BuletoothContentDTO>() {
        @Override
        public void complete(BuletoothContentDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(BuletoothContentDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void discoverCharacteristics(JSONObject obj, final CompletionHandler<Object> handler) {
      BtCharacteristicsDTO data= convert(obj,BtCharacteristicsDTO.class);
      _discoverCharacteristics(data, new CompletionHandler<BuletoothContentDTO>() {
        @Override
        public void complete(BuletoothContentDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(BuletoothContentDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void writeValueForCharacteristic(JSONObject obj, final CompletionHandler<Object> handler) {
      BtCharacteristicIdDTO data= convert(obj,BtCharacteristicIdDTO.class);
      _writeValueForCharacteristic(data, new CompletionHandler<BuletoothContentDTO>() {
        @Override
        public void complete(BuletoothContentDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(BuletoothContentDTO value) { handler.setProgressData(value); }
      });

    }

    @JavascriptInterface
    final public void readCharacteristic(JSONObject obj, final CompletionHandler<Object> handler) {
      BtCharacteristicIdDTO data= convert(obj,BtCharacteristicIdDTO.class);
      _readCharacteristic(data, new CompletionHandler<BuletoothContentDTO>() {
        @Override
        public void complete(BuletoothContentDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(BuletoothContentDTO value) { handler.setProgressData(value); }
      });

    }
  }
  

  