
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;
  import com.zkty.nativ.core.annotation.Optional;

  
  class NamedDTO {
    public String title;

    public Integer titleSize;
  }
  
  class _0_com_zkty_jsi_rn_direct_DTO {
    public String a;

    public _1_com_zkty_jsi_rn_direct_DTO i;
  }
  
  class _1_com_zkty_jsi_rn_direct_DTO {
    public String n1;
  }
  
  class _2_com_zkty_jsi_rn_direct_DTO {
    public String goodname;

    public Integer price;
  }
  
  class _3_com_zkty_jsi_rn_direct_DTO {
    public String name;

    public Integer age;
  }
  
  class _4_com_zkty_jsi_rn_direct_DTO {
    public String name;

    public Integer age;

    public List<_5_com_zkty_jsi_rn_direct_DTO> houses;
  }
  
  class _5_com_zkty_jsi_rn_direct_DTO {
    public String address;

    public String longtitude;

    public String latitude;

    public _6_com_zkty_jsi_rn_direct_DTO dealer;
  }
  
  class _6_com_zkty_jsi_rn_direct_DTO {
    public String name;

    public Integer age;
  }
  
  class _7_com_zkty_jsi_rn_direct_DTO {
    public String name;

    public Integer age;

    public List<_8_com_zkty_jsi_rn_direct_DTO> houses;
  }
  
  class _8_com_zkty_jsi_rn_direct_DTO {
    public String address;

    public String longtitude;

    public String latitude;

    public _9_com_zkty_jsi_rn_direct_DTO dealer;
  }
  
  class _9_com_zkty_jsi_rn_direct_DTO {
    public String name;

    public Integer age;
  }
  
  interface xengine_jsi_rn_direct_protocol {
    public void _simpleMethod(final CompletionHandler<Nullable> handler);
public void _simpleMethod();
public void _simpleArgMethod(String dto, final CompletionHandler<String> handler);
public String _simpleArgMethod(String dto);
public void _nestedAnonymousObject(final CompletionHandler<_0_com_zkty_jsi_rn_direct_DTO> handler);
public _0_com_zkty_jsi_rn_direct_DTO _nestedAnonymousObject();
public void _namedObject(final CompletionHandler<NamedDTO> handler);
public NamedDTO _namedObject();
public void _namedObjectWithNamedArgs(NamedDTO dto, final CompletionHandler<NamedDTO> handler);
public NamedDTO _namedObjectWithNamedArgs(NamedDTO dto);
public void _namedObjectWithArgs(_3_com_zkty_jsi_rn_direct_DTO dto, final CompletionHandler<_2_com_zkty_jsi_rn_direct_DTO> handler);
public _2_com_zkty_jsi_rn_direct_DTO _namedObjectWithArgs(_3_com_zkty_jsi_rn_direct_DTO dto);
public void _complexAnoymousRetWithAnoymousArgs(_7_com_zkty_jsi_rn_direct_DTO dto, final CompletionHandler<_4_com_zkty_jsi_rn_direct_DTO> handler);
public _4_com_zkty_jsi_rn_direct_DTO _complexAnoymousRetWithAnoymousArgs(_7_com_zkty_jsi_rn_direct_DTO dto);
  }
  
  
    public abstract class xengine_jsi_rn_direct extends JSIModule implements xengine_jsi_rn_direct_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.rn_direct";
    }
  
    @JavascriptInterface
    final public void simpleMethod(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _simpleMethod(new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
        @JavascriptInterface
        public Object simpleMethod(JSONObject jsonobj) {
          
          _simpleMethod();
          return null;
        }
        

    @JavascriptInterface
    final public void simpleArgMethod(String dto, final CompletionHandler<Object> handler) {
      
      _simpleArgMethod(dto, new CompletionHandler<String>() {
        @Override
        public void complete(String retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(String value) { handler.setProgressData(value); }
      });

    }
        @JavascriptInterface
        public String simpleArgMethod(String dto) {
          
          return _simpleArgMethod(dto);
        }
        

    @JavascriptInterface
    final public void nestedAnonymousObject(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _nestedAnonymousObject(new CompletionHandler<_0_com_zkty_jsi_rn_direct_DTO>() {
        @Override
        public void complete(_0_com_zkty_jsi_rn_direct_DTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(_0_com_zkty_jsi_rn_direct_DTO value) { handler.setProgressData(value); }
      });

    }
        @JavascriptInterface
        public _0_com_zkty_jsi_rn_direct_DTO nestedAnonymousObject(JSONObject jsonobj) {
          
          return _nestedAnonymousObject();
        }
        

    @JavascriptInterface
    final public void namedObject(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _namedObject(new CompletionHandler<NamedDTO>() {
        @Override
        public void complete(NamedDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(NamedDTO value) { handler.setProgressData(value); }
      });

    }
        @JavascriptInterface
        public NamedDTO namedObject(JSONObject jsonobj) {
          
          return _namedObject();
        }
        

    @JavascriptInterface
    final public void namedObjectWithNamedArgs(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      NamedDTO dto= convert(jsonobj,NamedDTO.class);
      _namedObjectWithNamedArgs(dto, new CompletionHandler<NamedDTO>() {
        @Override
        public void complete(NamedDTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(NamedDTO value) { handler.setProgressData(value); }
      });

    }
        @JavascriptInterface
        public NamedDTO namedObjectWithNamedArgs(JSONObject jsonobj) {
          NamedDTO dto= convert(jsonobj,NamedDTO.class);
          return _namedObjectWithNamedArgs(dto);
        }
        

    @JavascriptInterface
    final public void namedObjectWithArgs(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _3_com_zkty_jsi_rn_direct_DTO dto= convert(jsonobj,_3_com_zkty_jsi_rn_direct_DTO.class);
      _namedObjectWithArgs(dto, new CompletionHandler<_2_com_zkty_jsi_rn_direct_DTO>() {
        @Override
        public void complete(_2_com_zkty_jsi_rn_direct_DTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(_2_com_zkty_jsi_rn_direct_DTO value) { handler.setProgressData(value); }
      });

    }
        @JavascriptInterface
        public _2_com_zkty_jsi_rn_direct_DTO namedObjectWithArgs(JSONObject jsonobj) {
          _3_com_zkty_jsi_rn_direct_DTO dto= convert(jsonobj,_3_com_zkty_jsi_rn_direct_DTO.class);
          return _namedObjectWithArgs(dto);
        }
        

    @JavascriptInterface
    final public void complexAnoymousRetWithAnoymousArgs(JSONObject jsonobj, final CompletionHandler<Object> handler) {
      _7_com_zkty_jsi_rn_direct_DTO dto= convert(jsonobj,_7_com_zkty_jsi_rn_direct_DTO.class);
      _complexAnoymousRetWithAnoymousArgs(dto, new CompletionHandler<_4_com_zkty_jsi_rn_direct_DTO>() {
        @Override
        public void complete(_4_com_zkty_jsi_rn_direct_DTO retValue) { handler.complete(retValue); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(_4_com_zkty_jsi_rn_direct_DTO value) { handler.setProgressData(value); }
      });

    }
        @JavascriptInterface
        public _4_com_zkty_jsi_rn_direct_DTO complexAnoymousRetWithAnoymousArgs(JSONObject jsonobj) {
          _7_com_zkty_jsi_rn_direct_DTO dto= convert(jsonobj,_7_com_zkty_jsi_rn_direct_DTO.class);
          return _complexAnoymousRetWithAnoymousArgs(dto);
        }
        
  }
  

  