# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
source 'https://github.com/CocoaPods/Specs.git'

# 在环境变量里指向 x-engine 本地路径
# export X_ENGINE_MODULES=/Users/zk/git/company/working/x-engine/modules

X_ENGINE_MODULES=ENV['X_ENGINE_MODULES'] || '../..'

def shared_pods
  pod 'x-engine-native-core', :path => X_ENGINE_MODULES+'/x-engine-native-core'
  pod 'x-engine-native-protocols', :path => X_ENGINE_MODULES+'/x-engine-native-protocols'
  
  pod 'x-engine-jsi-globalstorage', :path => X_ENGINE_MODULES+'/x-engine-jsi-globalstorage'
  pod 'x-engine-native-jsi', :path => X_ENGINE_MODULES+'/x-engine-native-jsi'
  pod 'x-engine-native-scan', :path => X_ENGINE_MODULES+'/x-engine-native-scan'

  pod 'MGJRouter', '~>0.9.0'

end

target 'direct_native' do
  #use_frameworks!
  shared_pods
end
target 'direct_nativeTests' do
  #use_frameworks!
  shared_pods
end
target 'direct_nativeUITests' do
  # Pods for testing
  shared_pods

end
