
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import android.webkit.JavascriptInterface;

  import com.zkty.nativ.jsi.JSIModule;


interface xengine_jsi_dev_protocol {
    
public void _log(String dto);
  }
  
  
    public abstract class xengine_jsi_dev extends JSIModule implements xengine_jsi_dev_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.jsi.dev";
    }
  
        @JavascriptInterface
        public Object log(String dto) {
          
          _log(dto);
          return null;
        }
        
  }
  

  