# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'nav' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # use private repo
#  source 'https://github.com/CocoaPods/Specs.git'
#  source 'https://github.com/zkty-team/x-engine-pods.git'


  pod 'x-engine-module-engine', :path =>'../../x-engine-module-engine/'
  pod 'x-engine-module-protocols', :path =>'../../x-engine-module-protocols/'
  pod 'x-engine-module-network', :path =>'../../x-engine-module-network/'
  pod 'x-engine-module-tools', :path =>'../../x-engine-module-tools/'

  target 'navUITests' do
    # Pods for testing
  end

end
