// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.yjzdbill", 
    [
  {
    "name": "YJBillPayment",
    "default_args": {
      "appScheme": "x-engine",
      "payType": false
    }
  },
  {
    "name": "YJBillRefund",
    "default_args": null
  },
  {
    "name": "YJBillList",
    "default_args": null
  }
]
)}}

export default osCheck();
