// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.yjzdbill", 
    [
  {
    "name": "echo",
    "default_args": null
  },
  {
    "name": "YJBillPayment",
    "default_args": {
      "businessCstNo": "000001",
      "platMerCstNo": "8377631273379692750",
      "tradeMerCstNo": "8377707718294634760",
      "billNo": "022020120416543228724452ba399222",
      "appScheme": "zdsdk",
      "payType": false
    }
  },
  {
    "name": "YJBillRefund",
    "default_args": {
      "refundOrderNo": "RFO1607064781790"
    }
  },
  {
    "name": "YJBillList",
    "default_args": {
      "businessCstNo": "000001",
      "appScheme": "zdsdk",
      "payType": false
    }
  }
]
)}}

export default osCheck();
