// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.direct", 
    [
  {
    "name": "broadcastOn",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "broadcastOff",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "triggerNativeBroadCast",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "repeatReturn__event__",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "repeatReturn__ret__",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "ReturnInPromiseThen",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
