
// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!

  package com.zkty.jsi;

  import java.util.List;
  import java.util.Map;
  import java.util.Set;
  import android.webkit.JavascriptInterface;
  import com.alibaba.fastjson.JSON;
  import com.alibaba.fastjson.JSONObject;
  import com.zkty.modules.nativ.jsi.bridge.CompletionHandler;
  import com.zkty.modules.nativ.jsi.JSIModule;
  import androidx.annotation.Nullable;

  
  class ScanOpenDto {
    public String __event__;
  }
  
  interface xengine_module_scan_protocol {
    public void _openScanView(ScanOpenDto dto, final CompletionHandler<Nullable> handler);
  }
  
  
  public abstract class xengine_module_scan extends JSIModule implements xengine_module_scan_protocol {
    @Override
    public String moduleId() {
      return "com.zkty.module.scan";
    }
  
    @JavascriptInterface
    final public void openScanView(JSONObject obj, final CompletionHandler<Object> handler) {
      ScanOpenDto data= convert(obj,ScanOpenDto.class);
      _openScanView(data, new CompletionHandler<Nullable>() {
        @Override
        public void complete(Nullable retValue) { handler.complete(null); }
        @Override
        public void complete() { handler.complete(); }
        @Override
        public void setProgressData(Nullable value) { handler.setProgressData(null); }
      });

    }
  }
  

  