default_platform(:ios)

require 'plist'
platform :ios do
  lane :build do
    xcodeproj = "xxxx.xcodeproj" 
    scheme    = "xxxx"
    info = Plist.parse_xml('../xxxx/Info.plist')
    buildversion = info["CFBundleVersion"]
    version = get_version_number(xcodeproj: xcodeproj, target:scheme)

    build_app(
      scheme: scheme,
      export_xcargs: "-allowProvisioningUpdates",
      export_method: "development"
    )
  end
end
