# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zkty-team/x-engine-pods.git'

target 'tools' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  #pod 'JSONModel'
  #pod 'SSZipArchive'
  #pod 'AFNetworking'
  #pod 'XEngineSDK'
  #pod 'UIModule'
		
 
# Pods for XEngineSDK
# 在开发时,将所有依赖的 module 包放这.包括依赖的依赖
  pod 'x-engine-module-engine', :path =>'../../x-engine-module-engine'
#  pod 'x-engine-module-network', :path =>'../../x-engine-module-network'
#  pod 'x-engine-module-nav', :path =>'../../x-engine-module-nav'
  pod 'x-engine-module-microapp', :path =>'../../x-engine-module-microapp'
  

  target 'toolsUITests' do
    # Pods for testing
  end

end
