# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
 
#source 'https://github.com/CocoaPods/Specs.git'

#load './ModulePods.rb'
target 'router' do
  #use_frameworks!

  #module_pods
  pod 'SDWebImage'
  pod 'x-engine-module-engine', :path =>'../../x-engine-module-engine'
  pod 'x-engine-module-protocols', :path =>'../../x-engine-module-protocols'
  pod 'x-engine-module-nav', :path =>'../../x-engine-module-nav'
  pod 'x-engine-module-tools', :path =>'../../x-engine-module-tools'
  pod 'x-engine-module-dcloud', :path =>'../../x-engine-module-dcloud'
  pod 'UniBoost', :path => '../../../../UniBoost'


  pod 'WechatOpenSDK'

  target 'routerUITests' do
    # Pods for testing
  end

end
