// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (!xengine.hybrid) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.router", 
    [
  {
    "name": "openTargetRouter",
    "default_args": {
      "type": "0",
      "uri": "https://www.baidu.com",
      "path": ""
    }
  }
]
)}}

export default osCheck();
