// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-module-engine";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.module.router", 
    [
  {
    "name": "openTargetRouter",
    "default_args": {
      "type": "h5",
      "uri": "https://www.baidu.com",
      "path": ""
    }
  },
  {
    "name": "_testh5",
    "default_args": null
  },
  {
    "name": "_testnative",
    "default_args": null
  },
  {
    "name": "_testmicroapp",
    "default_args": null
  },
  {
    "name": "_testuni",
    "default_args": null
  }
]
)}}

export default osCheck();
