// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-core";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.xxxx", 
    [
  {
    "name": "syncMethod",
    "default_args": {
      "titleSize": 16
    },
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "syncStringMethod",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "syncMethod1",
    "default_args": {},
    "decorators": [
      "sync"
    ]
  },
  {
    "name": "asyncMethod",
    "default_args": {
      "name": "default value"
    },
    "decorators": [
      "async"
    ]
  }
]
)}}

export default osCheck();
