// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!


import xengine from "@zkty-team/x-engine-core";
import mock from "./mock";
function osCheck() {
  if (false) {
    return mock;
} 
  else {

    return  xengine.use("com.zkty.jsi.xxxx", 
    [
  {
    "name": "test_同步无返回",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_同步返回命名对象",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_同步返回匿名嵌套对象",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_异步返回命名对象",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_异步返回命名对象",
    "default_args": {},
    "decorators": []
  },
  {
    "name": "test_异步返回匿名嵌套对象",
    "default_args": {},
    "decorators": []
  }
]
)}}

export default osCheck();
